### ISSUE TITLE
macOS vbcc vscode

### ISSUE THREAD

**Issue by ouya99** [weiju/amiga_hardware_in_c#2]
Hi, 

found your youtube series, appreciate it! and would like to test it on a mac.
Could not really make it work last year when I first tried with VBCC and KS1.3 + libs. Something of my setup was wrong. While I could start up "helloWorld" and even some intuition-gui programs, linking with gfx, audio libs never worked for me.
Could you please upload a setup for mac (in case you have one) which works with VBCC and VSCODE. 

Thank you

**Comment by weiju** [comment]
Hi thank you for your input ! Could you please provide me with a little more information about your setup ? I actually currently work on a Macbook Air m1 most of the time and have used it to write the examples for my past 3 or 4 videos. 
However, you need to make sure that your environment variables are all set correctly in order for the Makefile to work.
The most important environment variable is the path to your NDK include files.
Mine are set to

export NDK_INC=~/Development/amigadev/NDK_3.9/Include/include_h
export NDK_ASMINC=~/Development/amigadev/NDK_3.9/Include/include_i

On my Mac I have put this line into my .zshrc, because ZSH seems to be Apple's default terminal shell.

which can be  in a different location on your system. Depends on where you unpacked your NDK to. I regularly compile between Linux, MacOS X and Windows 10 (in the Ubuntu console), and it works everywhere I am using it, by opening a terminal window, going to the source directory and typing "make".

I don't have much experience using VS Code, I only use it to display source code in my videos, but I can see that it has an extension for using Makefiles.

**Comment by ouya99** [comment]
Hi, I have a macbook air m1 as well :)

Last year I tested it on my old macbook air and did download lots of demos and tutorials. 
Specifically I had trouble loading includes and libs and linking those. Most of the samples resulted in a crash on startup with a generic error, but some worked. I will try to set it up again. I remember having issues with the Makefile and Linker using NDK_3.9. Some kick13 libs existed in v3.9 and some did not. I targeted kick13 (OCS) but could not find all the libs/files that were needed for the samples in the NDK_3.9. So some c source files (kick13 demos) would not work with that version. So I was clueless and thought I had chosen the wrong libs (NDK) or had misconfigured the Makefile to launch a kick13 version

Could you maybe provide a set of all the lib files (NDK) that you are using for your samples? Or a link to the NDK you have been using so that I do not search in vain for bugs in a corrupt NDK which result in crashes on startup.

**Comment by weiju** [comment]
Hi,

the official Amiga NDK is still available at https://www.haage-partner.de/download/AmigaOS/NDK39.lha

It's the same as in the description of my video "Cross Development for the Amiga with VBCC"

Also, please make sure that you have set your VBCC environment variable to the location where your VBCC is installed, the compiler needs that to locate the targets and configuration files.

So for example my VBCC variable is set to ~/local/vbcc-0.9f

And the contents should look about like that, please make sure that the targets
directory structure is correct, otherwise you might run into linker issues


weiju@monokuma ~/local/vbcc-0.9f $ ls
bin  config  targets
weiju@monokuma ~/local/vbcc-0.9f $ ls targets/
m68k-amigaos  m68k-kick13
weiju@monokuma ~/local/vbcc-0.9f $ ls targets/m68k-kick13/
include  lib
weiju@monokuma ~/local/vbcc-0.9f $ 

Hope that helps !
